[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.92"
candle-core = { version = "0.7.2", features = ["cuda"] }
candle-nn = { version = "0.7.2", features = ["cuda"] }
candle-transformers = { version = "0.7.2", features = ["cuda"] }
serde_json = "1.0.132"
tokenizers = "0.20.1"
