name: cargo fmt on push
run-name: ${{ github.actor }} has triggered a cargo fmt, doin' it now!
on: [push]
jobs:
  check-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run formatter on project `master`
        run: cargo fmt --all

      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: CI auto-formatter
          CI_COMMIT_AUTHOR: CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
       
