name: cargo fmt on push
run-name: ${{ github.actor }} has triggered a cargo fmt, doin' it now!
on: [push]
jobs:
  check-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check that code can compile
        uses: cargo check

      - name: Run formatter
        uses: cargo fmt
